on:
  push:
    branches:
      - main
jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Create dir
        run: |
          mkdir testArtifacts
#Config environement

      - name: Install Newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
      - name: Run Test
        run: newman run Portal_TESTES_API.postman_collection.json -e Testes.postman_environment.json -r cli,html,htmlextra
        
      - name: Report
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Reports
          path: newman
